'use client' // This is necessary for the responsive component to work
import { ResponsiveBar } from '@nivo/bar'


// Dummy data for the chart
const data = [
    {
      "country": "AD",
      "hot dog": 63,
      "burger": 172,
      "sandwich": 33,
      "kebab": 121,
      "fries": 183,
      "donut": 149,
      "junk": 20,
      "sushi": 120,
      "ramen": 81,
      "curry": 43,
      "udon": 26,
      "bagel": 79,
      "yakitori": 36,
      "takoyaki": 69,
      "tacos": 10,
      "miso soup": 130,
      "tortilla": 188,
      "tapas": 74
    },
    {
      "country": "AE",
      "hot dog": 82,
      "burger": 187,
      "sandwich": 177,
      "kebab": 160,
      "fries": 39,
      "donut": 173,
      "junk": 115,
      "sushi": 4,
      "ramen": 89,
      "curry": 90,
      "udon": 197,
      "bagel": 17,
      "yakitori": 82,
      "takoyaki": 60,
      "tacos": 75,
      "miso soup": 53,
      "tortilla": 107,
      "tapas": 17
    },
    {
      "country": "AF",
      "hot dog": 176,
      "burger": 80,
      "sandwich": 111,
      "kebab": 88,
      "fries": 59,
      "donut": 111,
      "junk": 69,
      "sushi": 116,
      "ramen": 200,
      "curry": 132,
      "udon": 165,
      "bagel": 119,
      "yakitori": 192,
      "takoyaki": 74,
      "tacos": 179,
      "miso soup": 150,
      "tortilla": 34,
      "tapas": 164
    },
    {
      "country": "AG",
      "hot dog": 44,
      "burger": 124,
      "sandwich": 136,
      "kebab": 65,
      "fries": 73,
      "donut": 186,
      "junk": 169,
      "sushi": 45,
      "ramen": 188,
      "curry": 166,
      "udon": 26,
      "bagel": 49,
      "yakitori": 115,
      "takoyaki": 134,
      "tacos": 140,
      "miso soup": 40,
      "tortilla": 4,
      "tapas": 198
    },
    {
      "country": "AI",
      "hot dog": 120,
      "burger": 47,
      "sandwich": 131,
      "kebab": 63,
      "fries": 194,
      "donut": 165,
      "junk": 50,
      "sushi": 91,
      "ramen": 20,
      "curry": 92,
      "udon": 50,
      "bagel": 106,
      "yakitori": 56,
      "takoyaki": 181,
      "tacos": 151,
      "miso soup": 96,
      "tortilla": 116,
      "tapas": 121
    },
    {
      "country": "AL",
      "hot dog": 133,
      "burger": 108,
      "sandwich": 46,
      "kebab": 118,
      "fries": 45,
      "donut": 62,
      "junk": 62,
      "sushi": 13,
      "ramen": 51,
      "curry": 1,
      "udon": 162,
      "bagel": 196,
      "yakitori": 53,
      "takoyaki": 105,
      "tacos": 0,
      "miso soup": 85,
      "tortilla": 106,
      "tapas": 106
    },
    {
      "country": "AM",
      "hot dog": 131,
      "burger": 156,
      "sandwich": 10,
      "kebab": 111,
      "fries": 116,
      "donut": 177,
      "junk": 55,
      "sushi": 107,
      "ramen": 181,
      "curry": 57,
      "udon": 132,
      "bagel": 171,
      "yakitori": 37,
      "takoyaki": 173,
      "tacos": 93,
      "miso soup": 144,
      "tortilla": 27,
      "tapas": 94
    },
    {
      "country": "AO",
      "hot dog": 37,
      "burger": 119,
      "sandwich": 31,
      "kebab": 152,
      "fries": 171,
      "donut": 154,
      "junk": 101,
      "sushi": 200,
      "ramen": 1,
      "curry": 161,
      "udon": 3,
      "bagel": 2,
      "yakitori": 55,
      "takoyaki": 31,
      "tacos": 80,
      "miso soup": 181,
      "tortilla": 129,
      "tapas": 120
    },
    {
      "country": "AQ",
      "hot dog": 145,
      "burger": 7,
      "sandwich": 155,
      "kebab": 113,
      "fries": 77,
      "donut": 37,
      "junk": 193,
      "sushi": 29,
      "ramen": 91,
      "curry": 77,
      "udon": 101,
      "bagel": 77,
      "yakitori": 116,
      "takoyaki": 190,
      "tacos": 87,
      "miso soup": 33,
      "tortilla": 26,
      "tapas": 156
    },
    {
      "country": "AR",
      "hot dog": 162,
      "burger": 126,
      "sandwich": 169,
      "kebab": 145,
      "fries": 181,
      "donut": 11,
      "junk": 7,
      "sushi": 10,
      "ramen": 15,
      "curry": 5,
      "udon": 115,
      "bagel": 107,
      "yakitori": 176,
      "takoyaki": 4,
      "tacos": 196,
      "miso soup": 22,
      "tortilla": 88,
      "tapas": 87
    },
    {
      "country": "AS",
      "hot dog": 115,
      "burger": 155,
      "sandwich": 158,
      "kebab": 31,
      "fries": 183,
      "donut": 175,
      "junk": 19,
      "sushi": 53,
      "ramen": 166,
      "curry": 86,
      "udon": 67,
      "bagel": 163,
      "yakitori": 184,
      "takoyaki": 84,
      "tacos": 44,
      "miso soup": 70,
      "tortilla": 12,
      "tapas": 26
    },
    {
      "country": "AT",
      "hot dog": 97,
      "burger": 0,
      "sandwich": 14,
      "kebab": 118,
      "fries": 147,
      "donut": 192,
      "junk": 177,
      "sushi": 57,
      "ramen": 29,
      "curry": 25,
      "udon": 44,
      "bagel": 62,
      "yakitori": 18,
      "takoyaki": 196,
      "tacos": 179,
      "miso soup": 200,
      "tortilla": 194,
      "tapas": 179
    },
    {
      "country": "AU",
      "hot dog": 88,
      "burger": 36,
      "sandwich": 0,
      "kebab": 93,
      "fries": 13,
      "donut": 139,
      "junk": 13,
      "sushi": 111,
      "ramen": 164,
      "curry": 181,
      "udon": 174,
      "bagel": 170,
      "yakitori": 111,
      "takoyaki": 102,
      "tacos": 181,
      "miso soup": 0,
      "tortilla": 152,
      "tapas": 136
    },
    {
      "country": "AW",
      "hot dog": 106,
      "burger": 166,
      "sandwich": 18,
      "kebab": 123,
      "fries": 168,
      "donut": 87,
      "junk": 168,
      "sushi": 86,
      "ramen": 186,
      "curry": 143,
      "udon": 104,
      "bagel": 7,
      "yakitori": 118,
      "takoyaki": 2,
      "tacos": 126,
      "miso soup": 2,
      "tortilla": 112,
      "tapas": 56
    },
    {
      "country": "AX",
      "hot dog": 96,
      "burger": 149,
      "sandwich": 147,
      "kebab": 140,
      "fries": 31,
      "donut": 2,
      "junk": 1,
      "sushi": 170,
      "ramen": 185,
      "curry": 51,
      "udon": 150,
      "bagel": 159,
      "yakitori": 75,
      "takoyaki": 143,
      "tacos": 127,
      "miso soup": 151,
      "tortilla": 174,
      "tapas": 141
    },
    {
      "country": "AZ",
      "hot dog": 165,
      "burger": 29,
      "sandwich": 83,
      "kebab": 25,
      "fries": 134,
      "donut": 198,
      "junk": 89,
      "sushi": 160,
      "ramen": 65,
      "curry": 14,
      "udon": 22,
      "bagel": 129,
      "yakitori": 58,
      "takoyaki": 15,
      "tacos": 2,
      "miso soup": 26,
      "tortilla": 99,
      "tapas": 2
    },
    {
      "country": "BA",
      "hot dog": 67,
      "burger": 174,
      "sandwich": 25,
      "kebab": 44,
      "fries": 57,
      "donut": 56,
      "junk": 144,
      "sushi": 73,
      "ramen": 87,
      "curry": 27,
      "udon": 56,
      "bagel": 91,
      "yakitori": 103,
      "takoyaki": 154,
      "tacos": 187,
      "miso soup": 142,
      "tortilla": 115,
      "tapas": 79
    },
    {
      "country": "BB",
      "hot dog": 174,
      "burger": 55,
      "sandwich": 121,
      "kebab": 3,
      "fries": 198,
      "donut": 169,
      "junk": 1,
      "sushi": 124,
      "ramen": 173,
      "curry": 88,
      "udon": 162,
      "bagel": 138,
      "yakitori": 169,
      "takoyaki": 7,
      "tacos": 53,
      "miso soup": 44,
      "tortilla": 92,
      "tapas": 192
    },
    {
      "country": "BD",
      "hot dog": 82,
      "burger": 82,
      "sandwich": 143,
      "kebab": 62,
      "fries": 197,
      "donut": 165,
      "junk": 102,
      "sushi": 73,
      "ramen": 4,
      "curry": 183,
      "udon": 44,
      "bagel": 187,
      "yakitori": 94,
      "takoyaki": 182,
      "tacos": 48,
      "miso soup": 57,
      "tortilla": 31,
      "tapas": 130
    },
    {
      "country": "BE",
      "hot dog": 4,
      "burger": 98,
      "sandwich": 78,
      "kebab": 91,
      "fries": 144,
      "donut": 22,
      "junk": 74,
      "sushi": 175,
      "ramen": 56,
      "curry": 181,
      "udon": 36,
      "bagel": 125,
      "yakitori": 31,
      "takoyaki": 7,
      "tacos": 170,
      "miso soup": 24,
      "tortilla": 66,
      "tapas": 41
    },
    {
      "country": "BF",
      "hot dog": 102,
      "burger": 140,
      "sandwich": 144,
      "kebab": 114,
      "fries": 83,
      "donut": 31,
      "junk": 37,
      "sushi": 186,
      "ramen": 87,
      "curry": 89,
      "udon": 153,
      "bagel": 163,
      "yakitori": 153,
      "takoyaki": 183,
      "tacos": 22,
      "miso soup": 90,
      "tortilla": 129,
      "tapas": 187
    }
  ]


  const MyBar = ({ data }: { data: any[] }) => (
    <ResponsiveBar
        data={data}
        keys={[
            'hot dog',
            'burger',
            'sandwich'
        ]}
        indexBy="country"
        margin={{ top: 50, right: 60, bottom: 50, left: 60 }}
        padding={0.15}
        layout="vertical"
        colors={{ scheme: 'red_blue' }}
        borderColor={{ from: 'color', modifiers: [['darker', 1.6]] }}
        axisTop={{}}
        axisBottom={{ legend: 'hours of day', legendOffset: 36 }}
        axisLeft={{ legend: 'hours of use', legendOffset: -40 }}
        enableGridX={true}
        enableGridY={false}
        labelSkipWidth={12}
        labelSkipHeight={12}
        labelTextColor={{ from: 'color', modifiers: [['darker', 1.6]] }}
    />
  );

export default function Dashboard() {
  return (
    <div style={{ height: '600px', width: '100%' }}>
      <MyBar data={data} />
    </div>
  );
}